language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
install:
  - npm install
  - npm install -g http-server
before_script:
  - bower install
  - cd json_feed
  - http-server
